name: Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Nix
        uses: cachix/install-nix-action@v31
      - name: Build and Test
        run: nix build
      - name: Fetch project version
        run: echo "VERSION=$(nix develop --command -- mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: cardio_generator-${{ env.VERSION }}
          path: result/share/cardio_generator/cardio_generator.jar
        env:
          VERSION: ${{ env.VERSION }}

      - name: Setup nushell
        uses: hustcer/setup-nu@v3
        with:
          version: "0.104"
      - name: Checkout badges branch
        uses: actions/checkout@v4
        with:
          ref: badges
          path: badges
      - name: Generate badges
        shell: nu {0}
        run: |
          let color = [[min, color]; [90, '4c1'], [80, '97CA00'], [70, 'a4a61d'], [60, 'dfb317'], [50, 'fe7d37'], [0, 'e05d44']]
          open result/cov.csv
            | math sum
            | transpose name value
            | group-by { $in.name | split row '_' | get 0 }
            | transpose name value
            | update value {|$row| ($row.value | get 1).value / ($row.value | math sum).value * 100 | math round --precision 1}
            | insert color {|$kv| $color | where min <= $kv.value | get 0.color}
            | each {|$row|
              http get $'https://img.shields.io/badge/($row.name | str downcase)-(($row.value | into string) + "%" | url encode)-($row.color)'
              | save -f ("badges/" + ($row.name | str downcase) + ".svg")
            }
      - name: Upload badges
        uses: EndBug/add-and-commit@v9
        with:
          add: ./*.svg
          cwd: badges
          new_branch: badges
          message: "Update badges"
          default_author: github_actions
